version: '3'

services:
  #postgresdb96:
  # image: postgres:9.6
  # ports:
  #   - "5432:5432"
  # environment:
  #   POSTGRES_USER: postgres
  #   POSTGRES_PASSWORD: nYNRWDXqmrAPT8EASZH9
  #   POSTGRES_DB: RecreatieVoetbalPWA
  # volumes:
  #   - ./data/postgres:/var/lib/postgresql/data

  dockertest:
    image: dhrtom/dockertest
    ports:
    - "5000:5000"
    environment:
      ASPNETCORE_URLS: http://+:5000